/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedDoctorRouteImport } from './routes/_authenticated/doctor'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppActivityRouteImport } from './routes/_authenticated/app.activity'
import { Route as AuthenticatedAppAssistantRouteImport } from './routes/_authenticated/app.assistant'
import { Route as AuthenticatedAppConsentRouteImport } from './routes/_authenticated/app.consent'
import { Route as AuthenticatedAppDoctorRouteImport } from './routes/_authenticated/app.doctor'
import { Route as AuthenticatedAppExploreRouteImport } from './routes/_authenticated/app.explore'
import { Route as AuthenticatedAppFirstAidRouteImport } from './routes/_authenticated/app.first-aid'
import { Route as AuthenticatedAppHospitalRouteImport } from './routes/_authenticated/app.hospital'
import { Route as AuthenticatedAppMedicinesRouteImport } from './routes/_authenticated/app.medicines'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppRecordsRouteImport } from './routes/_authenticated/app.records'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedDoctorIndexRouteImport } from './routes/_authenticated/doctor.index'
import { Route as AuthenticatedDoctorAiRouteImport } from './routes/_authenticated/doctor.ai'
import { Route as AuthenticatedDoctorAppointmentsRouteImport } from './routes/_authenticated/doctor.appointments'
import { Route as AuthenticatedDoctorConsentRouteImport } from './routes/_authenticated/doctor.consent'
import { Route as AuthenticatedDoctorPatientsRouteImport } from './routes/_authenticated/doctor.patients'
import { Route as AuthenticatedDoctorProfileRouteImport } from './routes/_authenticated/doctor.profile'
import { Route as AuthenticatedDoctorRequestsRouteImport } from './routes/_authenticated/doctor.requests'
import { Route as AuthenticatedAppAdminIndexRouteImport } from './routes/_authenticated/app.admin.index'
import { Route as AuthenticatedAppAdminDirectoryRouteImport } from './routes/_authenticated/app.admin.directory'
import { Route as AuthenticatedAppRecordsIndexRouteImport } from './routes/_authenticated/app.records.index'
import { Route as AuthenticatedAppRecordsEmergencyCardRouteImport } from './routes/_authenticated/app.records.emergency-card'
import { Route as AuthenticatedAppRecordsScanRouteImport } from './routes/_authenticated/app.records.scan'
import { Route as AuthenticatedDoctorPatientsIndexRouteImport } from './routes/_authenticated/doctor.patients.index'
import { Route as AuthenticatedDoctorPatientsPatientIdRouteImport } from './routes/_authenticated/doctor.patients.$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoctorRoute = AuthenticatedDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppActivityRoute =
  AuthenticatedAppActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAssistantRoute =
  AuthenticatedAppAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConsentRoute = AuthenticatedAppConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDoctorRoute = AuthenticatedAppDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppExploreRoute = AuthenticatedAppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFirstAidRoute =
  AuthenticatedAppFirstAidRouteImport.update({
    id: '/first-aid',
    path: '/first-aid',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHospitalRoute =
  AuthenticatedAppHospitalRouteImport.update({
    id: '/hospital',
    path: '/hospital',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMedicinesRoute =
  AuthenticatedAppMedicinesRouteImport.update({
    id: '/medicines',
    path: '/medicines',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRecordsRoute = AuthenticatedAppRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedDoctorIndexRoute =
  AuthenticatedDoctorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)
const AuthenticatedDoctorAiRoute = AuthenticatedDoctorAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedDoctorRoute,
} as any)
const AuthenticatedDoctorAppointmentsRoute =
  AuthenticatedDoctorAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)
const AuthenticatedDoctorConsentRoute =
  AuthenticatedDoctorConsentRouteImport.update({
    id: '/consent',
    path: '/consent',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)
const AuthenticatedDoctorPatientsRoute =
  AuthenticatedDoctorPatientsRouteImport.update({
    id: '/patients',
    path: '/patients',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)
const AuthenticatedDoctorProfileRoute =
  AuthenticatedDoctorProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)
const AuthenticatedDoctorRequestsRoute =
  AuthenticatedDoctorRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedDoctorRoute,
  } as any)
const AuthenticatedAppAdminIndexRoute =
  AuthenticatedAppAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminDirectoryRoute =
  AuthenticatedAppAdminDirectoryRouteImport.update({
    id: '/admin/directory',
    path: '/admin/directory',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRecordsIndexRoute =
  AuthenticatedAppRecordsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppRecordsRoute,
  } as any)
const AuthenticatedAppRecordsEmergencyCardRoute =
  AuthenticatedAppRecordsEmergencyCardRouteImport.update({
    id: '/emergency-card',
    path: '/emergency-card',
    getParentRoute: () => AuthenticatedAppRecordsRoute,
  } as any)
const AuthenticatedAppRecordsScanRoute =
  AuthenticatedAppRecordsScanRouteImport.update({
    id: '/scan',
    path: '/scan',
    getParentRoute: () => AuthenticatedAppRecordsRoute,
  } as any)
const AuthenticatedDoctorPatientsIndexRoute =
  AuthenticatedDoctorPatientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDoctorPatientsRoute,
  } as any)
const AuthenticatedDoctorPatientsPatientIdRoute =
  AuthenticatedDoctorPatientsPatientIdRouteImport.update({
    id: '/$patientId',
    path: '/$patientId',
    getParentRoute: () => AuthenticatedDoctorPatientsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/doctor': typeof AuthenticatedDoctorRouteWithChildren
  '/app/activity': typeof AuthenticatedAppActivityRoute
  '/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/app/consent': typeof AuthenticatedAppConsentRoute
  '/app/doctor': typeof AuthenticatedAppDoctorRoute
  '/app/explore': typeof AuthenticatedAppExploreRoute
  '/app/first-aid': typeof AuthenticatedAppFirstAidRoute
  '/app/hospital': typeof AuthenticatedAppHospitalRoute
  '/app/medicines': typeof AuthenticatedAppMedicinesRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/records': typeof AuthenticatedAppRecordsRouteWithChildren
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/doctor/ai': typeof AuthenticatedDoctorAiRoute
  '/doctor/appointments': typeof AuthenticatedDoctorAppointmentsRoute
  '/doctor/consent': typeof AuthenticatedDoctorConsentRoute
  '/doctor/patients': typeof AuthenticatedDoctorPatientsRouteWithChildren
  '/doctor/profile': typeof AuthenticatedDoctorProfileRoute
  '/doctor/requests': typeof AuthenticatedDoctorRequestsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/doctor/': typeof AuthenticatedDoctorIndexRoute
  '/app/admin/directory': typeof AuthenticatedAppAdminDirectoryRoute
  '/app/records/emergency-card': typeof AuthenticatedAppRecordsEmergencyCardRoute
  '/app/records/scan': typeof AuthenticatedAppRecordsScanRoute
  '/doctor/patients/$patientId': typeof AuthenticatedDoctorPatientsPatientIdRoute
  '/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/app/records/': typeof AuthenticatedAppRecordsIndexRoute
  '/doctor/patients/': typeof AuthenticatedDoctorPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app/activity': typeof AuthenticatedAppActivityRoute
  '/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/app/consent': typeof AuthenticatedAppConsentRoute
  '/app/doctor': typeof AuthenticatedAppDoctorRoute
  '/app/explore': typeof AuthenticatedAppExploreRoute
  '/app/first-aid': typeof AuthenticatedAppFirstAidRoute
  '/app/hospital': typeof AuthenticatedAppHospitalRoute
  '/app/medicines': typeof AuthenticatedAppMedicinesRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/doctor/ai': typeof AuthenticatedDoctorAiRoute
  '/doctor/appointments': typeof AuthenticatedDoctorAppointmentsRoute
  '/doctor/consent': typeof AuthenticatedDoctorConsentRoute
  '/doctor/profile': typeof AuthenticatedDoctorProfileRoute
  '/doctor/requests': typeof AuthenticatedDoctorRequestsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/doctor': typeof AuthenticatedDoctorIndexRoute
  '/app/admin/directory': typeof AuthenticatedAppAdminDirectoryRoute
  '/app/records/emergency-card': typeof AuthenticatedAppRecordsEmergencyCardRoute
  '/app/records/scan': typeof AuthenticatedAppRecordsScanRoute
  '/doctor/patients/$patientId': typeof AuthenticatedDoctorPatientsPatientIdRoute
  '/app/admin': typeof AuthenticatedAppAdminIndexRoute
  '/app/records': typeof AuthenticatedAppRecordsIndexRoute
  '/doctor/patients': typeof AuthenticatedDoctorPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/doctor': typeof AuthenticatedDoctorRouteWithChildren
  '/_authenticated/app/activity': typeof AuthenticatedAppActivityRoute
  '/_authenticated/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/_authenticated/app/consent': typeof AuthenticatedAppConsentRoute
  '/_authenticated/app/doctor': typeof AuthenticatedAppDoctorRoute
  '/_authenticated/app/explore': typeof AuthenticatedAppExploreRoute
  '/_authenticated/app/first-aid': typeof AuthenticatedAppFirstAidRoute
  '/_authenticated/app/hospital': typeof AuthenticatedAppHospitalRoute
  '/_authenticated/app/medicines': typeof AuthenticatedAppMedicinesRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/records': typeof AuthenticatedAppRecordsRouteWithChildren
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/doctor/ai': typeof AuthenticatedDoctorAiRoute
  '/_authenticated/doctor/appointments': typeof AuthenticatedDoctorAppointmentsRoute
  '/_authenticated/doctor/consent': typeof AuthenticatedDoctorConsentRoute
  '/_authenticated/doctor/patients': typeof AuthenticatedDoctorPatientsRouteWithChildren
  '/_authenticated/doctor/profile': typeof AuthenticatedDoctorProfileRoute
  '/_authenticated/doctor/requests': typeof AuthenticatedDoctorRequestsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/doctor/': typeof AuthenticatedDoctorIndexRoute
  '/_authenticated/app/admin/directory': typeof AuthenticatedAppAdminDirectoryRoute
  '/_authenticated/app/records/emergency-card': typeof AuthenticatedAppRecordsEmergencyCardRoute
  '/_authenticated/app/records/scan': typeof AuthenticatedAppRecordsScanRoute
  '/_authenticated/doctor/patients/$patientId': typeof AuthenticatedDoctorPatientsPatientIdRoute
  '/_authenticated/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/_authenticated/app/records/': typeof AuthenticatedAppRecordsIndexRoute
  '/_authenticated/doctor/patients/': typeof AuthenticatedDoctorPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/app'
    | '/doctor'
    | '/app/activity'
    | '/app/assistant'
    | '/app/consent'
    | '/app/doctor'
    | '/app/explore'
    | '/app/first-aid'
    | '/app/hospital'
    | '/app/medicines'
    | '/app/profile'
    | '/app/records'
    | '/app/settings'
    | '/doctor/ai'
    | '/doctor/appointments'
    | '/doctor/consent'
    | '/doctor/patients'
    | '/doctor/profile'
    | '/doctor/requests'
    | '/app/'
    | '/doctor/'
    | '/app/admin/directory'
    | '/app/records/emergency-card'
    | '/app/records/scan'
    | '/doctor/patients/$patientId'
    | '/app/admin/'
    | '/app/records/'
    | '/doctor/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/app/activity'
    | '/app/assistant'
    | '/app/consent'
    | '/app/doctor'
    | '/app/explore'
    | '/app/first-aid'
    | '/app/hospital'
    | '/app/medicines'
    | '/app/profile'
    | '/app/settings'
    | '/doctor/ai'
    | '/doctor/appointments'
    | '/doctor/consent'
    | '/doctor/profile'
    | '/doctor/requests'
    | '/app'
    | '/doctor'
    | '/app/admin/directory'
    | '/app/records/emergency-card'
    | '/app/records/scan'
    | '/doctor/patients/$patientId'
    | '/app/admin'
    | '/app/records'
    | '/doctor/patients'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/doctor'
    | '/_authenticated/app/activity'
    | '/_authenticated/app/assistant'
    | '/_authenticated/app/consent'
    | '/_authenticated/app/doctor'
    | '/_authenticated/app/explore'
    | '/_authenticated/app/first-aid'
    | '/_authenticated/app/hospital'
    | '/_authenticated/app/medicines'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/records'
    | '/_authenticated/app/settings'
    | '/_authenticated/doctor/ai'
    | '/_authenticated/doctor/appointments'
    | '/_authenticated/doctor/consent'
    | '/_authenticated/doctor/patients'
    | '/_authenticated/doctor/profile'
    | '/_authenticated/doctor/requests'
    | '/_authenticated/app/'
    | '/_authenticated/doctor/'
    | '/_authenticated/app/admin/directory'
    | '/_authenticated/app/records/emergency-card'
    | '/_authenticated/app/records/scan'
    | '/_authenticated/doctor/patients/$patientId'
    | '/_authenticated/app/admin/'
    | '/_authenticated/app/records/'
    | '/_authenticated/doctor/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor': {
      id: '/_authenticated/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AuthenticatedDoctorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/activity': {
      id: '/_authenticated/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AuthenticatedAppActivityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/assistant': {
      id: '/_authenticated/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AuthenticatedAppAssistantRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/consent': {
      id: '/_authenticated/app/consent'
      path: '/consent'
      fullPath: '/app/consent'
      preLoaderRoute: typeof AuthenticatedAppConsentRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/doctor': {
      id: '/_authenticated/app/doctor'
      path: '/doctor'
      fullPath: '/app/doctor'
      preLoaderRoute: typeof AuthenticatedAppDoctorRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/explore': {
      id: '/_authenticated/app/explore'
      path: '/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof AuthenticatedAppExploreRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/first-aid': {
      id: '/_authenticated/app/first-aid'
      path: '/first-aid'
      fullPath: '/app/first-aid'
      preLoaderRoute: typeof AuthenticatedAppFirstAidRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/hospital': {
      id: '/_authenticated/app/hospital'
      path: '/hospital'
      fullPath: '/app/hospital'
      preLoaderRoute: typeof AuthenticatedAppHospitalRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/medicines': {
      id: '/_authenticated/app/medicines'
      path: '/medicines'
      fullPath: '/app/medicines'
      preLoaderRoute: typeof AuthenticatedAppMedicinesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/records': {
      id: '/_authenticated/app/records'
      path: '/records'
      fullPath: '/app/records'
      preLoaderRoute: typeof AuthenticatedAppRecordsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/doctor/': {
      id: '/_authenticated/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof AuthenticatedDoctorIndexRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/doctor/ai': {
      id: '/_authenticated/doctor/ai'
      path: '/ai'
      fullPath: '/doctor/ai'
      preLoaderRoute: typeof AuthenticatedDoctorAiRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/doctor/appointments': {
      id: '/_authenticated/doctor/appointments'
      path: '/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof AuthenticatedDoctorAppointmentsRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/doctor/consent': {
      id: '/_authenticated/doctor/consent'
      path: '/consent'
      fullPath: '/doctor/consent'
      preLoaderRoute: typeof AuthenticatedDoctorConsentRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/doctor/patients': {
      id: '/_authenticated/doctor/patients'
      path: '/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof AuthenticatedDoctorPatientsRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/doctor/profile': {
      id: '/_authenticated/doctor/profile'
      path: '/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof AuthenticatedDoctorProfileRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/doctor/requests': {
      id: '/_authenticated/doctor/requests'
      path: '/requests'
      fullPath: '/doctor/requests'
      preLoaderRoute: typeof AuthenticatedDoctorRequestsRouteImport
      parentRoute: typeof AuthenticatedDoctorRoute
    }
    '/_authenticated/app/admin/': {
      id: '/_authenticated/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AuthenticatedAppAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin/directory': {
      id: '/_authenticated/app/admin/directory'
      path: '/admin/directory'
      fullPath: '/app/admin/directory'
      preLoaderRoute: typeof AuthenticatedAppAdminDirectoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/records/': {
      id: '/_authenticated/app/records/'
      path: '/'
      fullPath: '/app/records/'
      preLoaderRoute: typeof AuthenticatedAppRecordsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRecordsRoute
    }
    '/_authenticated/app/records/emergency-card': {
      id: '/_authenticated/app/records/emergency-card'
      path: '/emergency-card'
      fullPath: '/app/records/emergency-card'
      preLoaderRoute: typeof AuthenticatedAppRecordsEmergencyCardRouteImport
      parentRoute: typeof AuthenticatedAppRecordsRoute
    }
    '/_authenticated/app/records/scan': {
      id: '/_authenticated/app/records/scan'
      path: '/scan'
      fullPath: '/app/records/scan'
      preLoaderRoute: typeof AuthenticatedAppRecordsScanRouteImport
      parentRoute: typeof AuthenticatedAppRecordsRoute
    }
    '/_authenticated/doctor/patients/': {
      id: '/_authenticated/doctor/patients/'
      path: '/'
      fullPath: '/doctor/patients/'
      preLoaderRoute: typeof AuthenticatedDoctorPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedDoctorPatientsRoute
    }
    '/_authenticated/doctor/patients/$patientId': {
      id: '/_authenticated/doctor/patients/$patientId'
      path: '/$patientId'
      fullPath: '/doctor/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedDoctorPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedDoctorPatientsRoute
    }
  }
}

interface AuthenticatedAppRecordsRouteChildren {
  AuthenticatedAppRecordsEmergencyCardRoute: typeof AuthenticatedAppRecordsEmergencyCardRoute
  AuthenticatedAppRecordsScanRoute: typeof AuthenticatedAppRecordsScanRoute
  AuthenticatedAppRecordsIndexRoute: typeof AuthenticatedAppRecordsIndexRoute
}

const AuthenticatedAppRecordsRouteChildren: AuthenticatedAppRecordsRouteChildren =
  {
    AuthenticatedAppRecordsEmergencyCardRoute:
      AuthenticatedAppRecordsEmergencyCardRoute,
    AuthenticatedAppRecordsScanRoute: AuthenticatedAppRecordsScanRoute,
    AuthenticatedAppRecordsIndexRoute: AuthenticatedAppRecordsIndexRoute,
  }

const AuthenticatedAppRecordsRouteWithChildren =
  AuthenticatedAppRecordsRoute._addFileChildren(
    AuthenticatedAppRecordsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppActivityRoute: typeof AuthenticatedAppActivityRoute
  AuthenticatedAppAssistantRoute: typeof AuthenticatedAppAssistantRoute
  AuthenticatedAppConsentRoute: typeof AuthenticatedAppConsentRoute
  AuthenticatedAppDoctorRoute: typeof AuthenticatedAppDoctorRoute
  AuthenticatedAppExploreRoute: typeof AuthenticatedAppExploreRoute
  AuthenticatedAppFirstAidRoute: typeof AuthenticatedAppFirstAidRoute
  AuthenticatedAppHospitalRoute: typeof AuthenticatedAppHospitalRoute
  AuthenticatedAppMedicinesRoute: typeof AuthenticatedAppMedicinesRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppRecordsRoute: typeof AuthenticatedAppRecordsRouteWithChildren
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAdminDirectoryRoute: typeof AuthenticatedAppAdminDirectoryRoute
  AuthenticatedAppAdminIndexRoute: typeof AuthenticatedAppAdminIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppActivityRoute: AuthenticatedAppActivityRoute,
  AuthenticatedAppAssistantRoute: AuthenticatedAppAssistantRoute,
  AuthenticatedAppConsentRoute: AuthenticatedAppConsentRoute,
  AuthenticatedAppDoctorRoute: AuthenticatedAppDoctorRoute,
  AuthenticatedAppExploreRoute: AuthenticatedAppExploreRoute,
  AuthenticatedAppFirstAidRoute: AuthenticatedAppFirstAidRoute,
  AuthenticatedAppHospitalRoute: AuthenticatedAppHospitalRoute,
  AuthenticatedAppMedicinesRoute: AuthenticatedAppMedicinesRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppRecordsRoute: AuthenticatedAppRecordsRouteWithChildren,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAdminDirectoryRoute: AuthenticatedAppAdminDirectoryRoute,
  AuthenticatedAppAdminIndexRoute: AuthenticatedAppAdminIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedDoctorPatientsRouteChildren {
  AuthenticatedDoctorPatientsPatientIdRoute: typeof AuthenticatedDoctorPatientsPatientIdRoute
  AuthenticatedDoctorPatientsIndexRoute: typeof AuthenticatedDoctorPatientsIndexRoute
}

const AuthenticatedDoctorPatientsRouteChildren: AuthenticatedDoctorPatientsRouteChildren =
  {
    AuthenticatedDoctorPatientsPatientIdRoute:
      AuthenticatedDoctorPatientsPatientIdRoute,
    AuthenticatedDoctorPatientsIndexRoute:
      AuthenticatedDoctorPatientsIndexRoute,
  }

const AuthenticatedDoctorPatientsRouteWithChildren =
  AuthenticatedDoctorPatientsRoute._addFileChildren(
    AuthenticatedDoctorPatientsRouteChildren,
  )

interface AuthenticatedDoctorRouteChildren {
  AuthenticatedDoctorAiRoute: typeof AuthenticatedDoctorAiRoute
  AuthenticatedDoctorAppointmentsRoute: typeof AuthenticatedDoctorAppointmentsRoute
  AuthenticatedDoctorConsentRoute: typeof AuthenticatedDoctorConsentRoute
  AuthenticatedDoctorPatientsRoute: typeof AuthenticatedDoctorPatientsRouteWithChildren
  AuthenticatedDoctorProfileRoute: typeof AuthenticatedDoctorProfileRoute
  AuthenticatedDoctorRequestsRoute: typeof AuthenticatedDoctorRequestsRoute
  AuthenticatedDoctorIndexRoute: typeof AuthenticatedDoctorIndexRoute
}

const AuthenticatedDoctorRouteChildren: AuthenticatedDoctorRouteChildren = {
  AuthenticatedDoctorAiRoute: AuthenticatedDoctorAiRoute,
  AuthenticatedDoctorAppointmentsRoute: AuthenticatedDoctorAppointmentsRoute,
  AuthenticatedDoctorConsentRoute: AuthenticatedDoctorConsentRoute,
  AuthenticatedDoctorPatientsRoute:
    AuthenticatedDoctorPatientsRouteWithChildren,
  AuthenticatedDoctorProfileRoute: AuthenticatedDoctorProfileRoute,
  AuthenticatedDoctorRequestsRoute: AuthenticatedDoctorRequestsRoute,
  AuthenticatedDoctorIndexRoute: AuthenticatedDoctorIndexRoute,
}

const AuthenticatedDoctorRouteWithChildren =
  AuthenticatedDoctorRoute._addFileChildren(AuthenticatedDoctorRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedDoctorRoute: typeof AuthenticatedDoctorRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedDoctorRoute: AuthenticatedDoctorRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
